version: '3.4'

services:
    mysql:
        image: percona:5.7
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=sylius_mercanet_test
        volumes:
            - database:/var/lib/mysql:rw,cached
        command: mysqld --sql_mode="" --max_allowed_packet=325058560
        ports:
            - "3306:3306"

volumes:
    database: {}
