version: '3.4'

services:
    mysql:
        image: percona:5.7
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=sylius_plugin_dev
        volumes:
            - ./tests/Application/var/database:/var/lib/mysql:rw,delegated
        command: mysqld --sql_mode=""
        ports:
            - "12542:3306"

volumes:
    mysql-data:
