name: Quality Assurance

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

env:
    PHP_VERSION: 7.3
    APP_ENV: test

jobs:
    php:
        runs-on: ubuntu-latest
        steps:

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ env.PHP_VERSION }}
                    extensions: mbstring, intl

            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Composer Install
                run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

            -   name: Easy coding standard
                run: ./vendor/bin/ecs check ./src

            -   name: PHPStan
                run: ./vendor/bin/phpstan analyse -c phpstan.neon -l 3 ./src/

            -   name: PHPSpec
                run: ./vendor/bin/phpspec run

            -   name: Checks that the YAML config files contain no syntax errors
                run: (cd tests/Application && bin/console lint:yaml config --parse-tags)

            -   name: Checks that Doctrine's mapping configurations are valid
                run: (cd tests/Application && bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction)
